openapi: "3.0.0"
info:
  title: "ktor_repository_sample API"
  description: "ktor_repository_sample API"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"
  description: "Localhost server"
paths:
  /books:
    get:
      description: "used to fetch all the books from database"
      responses:
        "200":
          description: "OK <br> bookController.findAll(call)"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Book"
    post:
      description: "Create new Book"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
        required: true
      responses:
        "400":
          description: "Bad Request <br> call.respondText(text = \"500: $cause\",\
            \ status = HttpStatusCode.InternalServerError)"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
components:
  schemas:
    Book:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        title:
          type: "string"
        author:
          type: "string"